export const FETCH_REGISTER = 'FETCH_REGISTER';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILED = 'FETCH_REGISTER_FAILED';

export const DISCONNECT = 'DISCONNECT';

export const FETCH_MY_PROFILE = 'FETCH_MY_PROFILE';
export const FETCH_MY_PROFILE_SUCCESS = 'FETCH_MY_PROFILE_SUCCESS';
export const FETCH_MY_PROFILE_FAILED = 'FETCH_MY_PROFILE_FAILED';
